var prenom;
prenom = "Amine";
console.log(prenom);
prenom = "Test";
console.log(prenom);
const nomDeFamille = "Ben Farhat";
document.write(nomDeFamille);
var amine;
amine = "25";
var jawad;
jawad = 15;
var ben;
ben = 0.5;
var farhat;
farhat = true;
console.log(typeof amine);
console.log(typeof jawad);
console.log(typeof ben);
console.log(typeof farhat);
